export const GET_MINE_LIST = 'GET_MINE_LIST'
export const GET_MINE_LIST_SUCCESS = 'GET_MINE_LIST_SUCCESS'
export const GET_MINE_LIST_FAILURE = 'GET_MINE_LIST_FAILURE'
export const GET_STAFF_LIST = 'GET_STAFF_LIST'
export const GET_STAFF_LIST_SUCCESS = 'GET_STAFF_LIST_SUCCESS'
export const GET_STAFF_LIST_FAILURE = 'GET_STAFF_LIST_FAILURE'
export const GET_UNDERLING_LIST = 'GET_UNDERLING_LIST'
export const GET_UNDERLING_LIST_SUCCESS = 'GET_UNDERLING_LIST_SUCCESS'
export const GET_UNDERLING_LIST_FAILURE = 'GET_UNDERLING_LIST_FAILURE'


export const GET_CUS_DETAIL = 'GET_CUS_DETAIL'
export const GET_CUS_DETAIL_SUCCESS = 'GET_CUS_DETAIL_SUCCESS'
export const GET_CUS_DETAIL_FAILURE = 'GET_CUS_DETAIL_FAILURE'

